### ISSUE TITLE
Add $schema property to cluster and job config JSON

### ISSUE THREAD

**Issue by damienpontifex** [Azure/BatchAI#10]
Azure ARM templates all use a $schema property for their JSON schema definition. Is it possible for the Batch AI JSON config files to also utilise the JSON schema to simplify editing and creating configuration files to be used?

Currently the best way I've found to discover the appropriate properties for these is to look at the C# class definition and drill down into properties that way.

**Comment by AlexanderYukhanov** [comment]
Sure, we can do this. But how will this property help (does any tool support this property)?
BTW, here is the swagger specification for the BatchAI service: https://github.com/Azure/azure-rest-api-specs/blob/current/specification/batchai/resource-manager/Microsoft.BatchAI/2017-09-01-preview/BatchAI.json

**Comment by damienpontifex** [comment]
VS Code does for ARM template authoring using `"$schema": "https://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#"` in the JSON object. Provides error checking and intellisense

**Comment by AlexanderYukhanov** [comment]
Sure, in this case we will implement it. Thank you for the info!

**Comment by AlexanderYukhanov** [comment]
Started working on it and pushed a version to test. You can try it by specifying the following schema in your job.json
"$schema": "https://raw.githubusercontent.com/Azure/BatchAI/schema/schemas/2017-09-01-preview/job.json"

**Comment by AlexanderYukhanov** [comment]
Published the schema for job configuration validation and updated existing recipes.
