### ISSUE TITLE
Node.js API documentation links broken

### ISSUE THREAD

**Issue by hxlnt** [Azure/BatchAI#22]
Node.js API documentation link (http://azure.github.io/azure-sdk-for-node/azure-batchai/latest/) results in a 404 error.

Broken link found at http://azure.github.io/azure-sdk-for-node/azure-arm-batchai/latest/ and https://www.npmjs.com/package/azure-arm-batchai.

**Comment by AlexanderYukhanov** [comment]
Thanks, will fix it

**Comment by AlexanderYukhanov** [comment]
@hxlnt ,  cannot find this link on this repo. Where is it coming from?

**Comment by hxlnt** [comment]
See the two links I posted in the original issue post. These pages have links to "API reference documents," both of which are broken. Thanks.

**Comment by AlexanderYukhanov** [comment]
Confused-) I cannot find this link on this GitHub. The only link to Node.js is on https://github.com/Azure/BatchAI/blob/master/README.md and this link seems correct.

**Comment by hxlnt** [comment]
@AlexanderYukhanov Ah, I traced this back, and the broken links are actually originating from [azure/azure-sdk-for-node](https://github.com/Azure/azure-sdk-for-node)... will post the issue there. Thanks!
