### ISSUE TITLE
Can't authenticate to AAD

### ISSUE THREAD

**Issue by paulshealy1** [Azure/BatchAI#3]
I'm following the CNTK-GPU-Python notebook. The call to utilities.create_batchai_client fails with this error:

AuthenticationError: , InvalidClientIdError: (invalid_request) AADSTS90002: Tenant <snip> not found. This may happen if there are no active subscriptions for the tenant. Check with your subscription administrator.

I was able to fix it by editing utilities.py so the AAD URI domain was https://login.windows.net, and it worked fine.

**Comment by lliimsft** [comment]
Hi Paul, Thanks for reporting the issue. We have just pushed the fix.
