### ISSUE TITLE
Environment variable AZ_BATCHAI_NUM_GPUS is returning empty string

### ISSUE THREAD

**Issue by karolzak** [Azure/BatchAI#40]
Hi, while trying to setup a distributed learning job with TF I found out that `AZ_BATCHAI_NUM_GPUS` variable ([described here](https://github.com/Azure/BatchAI/blob/master/documentation/using-batchai-environment-variables.md)) doesnt exist and it returns an empty string:

Part of my `job.json` config:
```JSON
...
"masterCommandLineArgs": "--job_name=worker --num_gpus=$AZ_BATCHAI_NUM_GPUS
...
```

Error msg:
```
 error: argument --num_gpus: invalid int value: '' 
```

Either support that variable or fix the docs 😀 
Thanks!

CC: @AlexanderYukhanov

**Comment by AlexanderYukhanov** [comment]
thank you for reporting the issue, working on the fix
