### ISSUE TITLE
ImportError: No module named 'skopt'

### ISSUE THREAD

**Issue by kishanakbari21** [Azure/BatchAI#45]
I am using keras method for BatchAI training for my python script. Python script requires 'skopt' to be imported in that. 
I am getting error message saying,

/anaconda/envs/py35/lib/python3.5/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
Traceback (most recent call last):
  File "/mnt/batch/tasks/shared/LS_root/mounts/afs/KerasSamples/cnn_for_Azure.py", line 27, in <module>
    import skopt
ImportError: No module named 'skopt'

**Comment by AlexanderYukhanov** [comment]
You need to create your own docker image which includes skopt or setup it using jobpreparation task (see here https://github.com/Azure/BatchAI/blob/master/documentation/using-azure-cli-20.md#job-preparation-task or take a look at horovod recipe) which uses it.
e.g
 "jobPreparation": {
      "commandLine": "pip install scikit-optimize"
    },

**Comment by JamesHallam1** [comment]
I'm having this same error but I think it is because my path to the package skopt is wrong. I have installed scikit-optimizer through pip and conda in my virtual environment but I am unable to load the package.
