### ISSUE TITLE
new Batch AI cluster incorrectly mount to Blob File reference to Blob container

### ISSUE THREAD

**Issue by wtam** [Azure/BatchAI#55]
Background: 
my old batchAI workspace recently been moved by Azure to "migrated-eastus" and after all I can't put any job to the new migrated workspace and force me to re-create a new workspace.  So I;ve to re-create a new workspace and new cluster.  

Problem:
when creating the new cluster, I want to keep referencing my old Blob File reference storage acct.  and I realized the new cluster's Blob File reference storage seem asking for the blob container (Not the Blob File reference).  As I receive below error after the cluster create as it seems instead of looking my existing blob file reference folder, its  seem looking at the empty Blob container
Code: BFSMountError
Message: unable to mount blob fuse file system
Info - Azure Blob Container 'batchaidemofolder' doesn't exist

Can someone look into if its a bug?

**Comment by spdjudd** [comment]
I've not had to migrate workspace, but yesterday started getting a BFSMountError too - sounds like a different issue so I raised #56

**Comment by lliimsft** [comment]
@wtam It looks like we cannot repro this issue. Can you please show us how did you configure the mount volume in your job/cluster definition? Did you use python SDK, CLI or portal?

**Comment by wtam** [comment]
@lliimsft, I use the portal this time and my original cluster before mover by MSFT was use CLI.

Here's my job blob file reference and I wonder why its ask for container in File reference
![job_blob_filereference](https://user-images.githubusercontent.com/12905616/43619422-4a3fdace-9700-11e8-9d35-75035bd300a4.JPG)

and here's the blob File refence [Not Container!]
![blob_filereference](https://user-images.githubusercontent.com/12905616/43619425-544f2eca-9700-11e8-8e4c-eded454e44ca.JPG)

and here's job basic info

![job_cluster_basic_info](https://user-images.githubusercontent.com/12905616/43619447-7c37d8ce-9700-11e8-8665-be1a87b69811.JPG)

**Comment by wtam** [comment]
Thanks @LiLi, I got mixed up from the Az storage acct's File Reference from Blob.  Now pointing change the mount to File reference and its working
