### ISSUE TITLE
Do you support Windows?

### ISSUE THREAD

**Issue by lmiroslaw** [Azure/BatchAI#59]
More specifically do you support images with preinstalled GPU drivers?

>az batchai cluster create -n nc6 -g hpc-bis-temp -w quistart -s Standard_NC6 -i microsoft-ads:windows-data-science-vm:windows2016:latest -t 1  

triggered  the error:
>The specified value Publisher=microsoft-ads,Offer=windows-data-science-vm,SKU=windows2016 for property imageReference is not supported

**Comment by lliimsft** [comment]
@lmiroslaw  Sorry Batch AI currently does not support Windows image
