### ISSUE TITLE
Bash Recipe Setup Does Not Set "workspace"

### ISSUE THREAD

**Issue by marabout2015** [Azure/BatchAI#62]
Repro:
1. Run setup.sh, supplying correct answers.
1. Run through the second cell in notebook recipes/Hyperparameters/Random-Search/RandomSearch.ipynb
1. Observe the error message:
   ```
   ValidationError: Parameter 'workspace_name' must conform to the following pattern: '^[-\\w_]+$'.
   ```

**Comment by lliimsft** [comment]
@marabout2015  Thanks for reporting this. We have pushed a fix regarding to this issue.
